BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TblUSER" (
	"NOME"	TEXT,
	"NUMERO DE TELEFONE"	TEXT,
	"EMAIL"	TEXT,
	"ID_USER"	INTEGER NOT NULL,
	"ENDERECO"	TEXT,
	"CARGO"	TEXT
);
CREATE TABLE IF NOT EXISTS "TblEXPERIENCIA" (
	"NOME DA EMPRESA"	TEXT,
	"DATA INICIAL"	TEXT,
	"DATA FINAL"	TEXT,
	"CARGO"	TEXT,
	"DESCRICAO"	TEXT,
	"ID_EXPERIENCIA"	INTEGER NOT NULL,
	"ID_USER"	INTEGER,
	FOREIGN KEY("ID_USER") REFERENCES "TblUSER"("ID_USER"),
	PRIMARY KEY("ID_EXPERIENCIA")
);
CREATE TABLE IF NOT EXISTS "TblFORMACAO" (
	"CURSO"	TEXT,
	"DATA INICIAL"	TEXT,
	"DATA FINAL"	TEXT,
	"DESCRICAO"	TEXT,
	"ID_FORMACAO"	INTEGER NOT NULL,
	"ID_USER"	INTEGER,
	FOREIGN KEY("ID_USER") REFERENCES "TblUSER"("ID_USER"),
	PRIMARY KEY("ID_FORMACAO")
);
CREATE TABLE IF NOT EXISTS "TblHABILIDADE" (
	"TIPOS DE HABILIDADE"	TEXT,
	"NIVEIS"	TEXT,
	"ID_HABILIDADE"	INTEGER NOT NULL,
	"ID_USER"	INTEGER,
	FOREIGN KEY("ID_USER") REFERENCES "TblUSER"("ID_USER"),
	PRIMARY KEY("ID_HABILIDADE")
);
CREATE TABLE IF NOT EXISTS "TblPERSONALIDADE" (
	"TIPOS DE PERSONALIDADES"	TEXT,
	"NIVEIS"	TEXT,
	"ID_PERSONALIDADE"	INTEGER NOT NULL,
	"ID_USER"	INTEGER,
	FOREIGN KEY("ID_USER") REFERENCES "TblUSER"("ID_USER"),
	PRIMARY KEY("ID_PERSONALIDADE")
);
CREATE TABLE IF NOT EXISTS "TblREALIZACOES" (
	"NOME DA REALIZACAO"	TEXT,
	"DATA DA REALIZACAO"	TEXT,
	"DESCRICAO"	TEXT,
	"ID_REALIZACOES"	INTEGER NOT NULL,
	"ID_USER"	INTEGER,
	FOREIGN KEY("ID_USER") REFERENCES "TblUSER"("ID_USER"),
	PRIMARY KEY("ID_REALIZACOES")
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_TblHABILIDADE" ON "TblHABILIDADE" (
	"ID_HABILIDADE"
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_TblEXPERIENCIA" ON "TblEXPERIENCIA" (
	"ID_EXPERIENCIA"
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_TblFORMACAO" ON "TblFORMACAO" (
	"ID_FORMACAO"
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_TblPERSONALIDADE" ON "TblPERSONALIDADE" (
	"ID_PERSONALIDADE"
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_TblREALIZACOES" ON "TblREALIZACOES" (
	"ID_REALIZACOES"
);
CREATE UNIQUE INDEX IF NOT EXISTS "pk_TblUSER" ON "TblUSER" (
	"ID_USER"
);
COMMIT;